### ISSUE TITLE
Is this package needed any more?

### ISSUE THREAD

**Issue by zimme** [barbatus/typescript-runtime#1]
Since [this](https://github.com/Microsoft/TypeScript/issues/3364#issuecomment-248467357) has been resolved this package shouldn't be needed any more, right?

We should just be able to depend on `tslib` instead of this package and use `--importHelpers`.

**Comment by barbatus** [comment]
Good point. But there is still `module: none` supported, which means someone might need them defined globally. Probably this is very rare case in 1.4 and above, but still possible.
I though import and define helpers based on tslib in this package now.
Will see how it goes, likely I'll get rid of it in the near future.

**Comment by zimme** [comment]
I guess we can close this as it's still needed. 👍
